### ISSUE TITLE
Add search user page

### ISSUE THREAD

**Issue by andrelas1** [bitfindr/bitpoint#22] opened 2017-10-20 02:01 UTC

**Comment by navispeed** [comment] 2017-10-20 03:13
Hello, can you be more explicit ? 
There is already an search user page 😕

**Comment by yannbf** [comment] 2017-10-20 12:13
Hey @navispeed, thanks a lot for your interest! Actually this issue is a duplicate of #17, which was already solved. Sorry for the confusion, I'm closing it now.

In the meantime, there are other ways you could contribute, other issues and discussions, so feel free to try them! 😃

**Closed by yannbf** 2017-10-20 12:13 UTC
Labels: feature, Hacktoberfest
